application:
  artifactId: @application.artifactId@
  version: @application.version@
server:
  port: 8080

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: @application.name@
#    mvc:
#      pathmatch:
#        matching-strategy: ant_path_matcher
#    webflux.base-path: /api
#    datasource:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost/postgres
#      username: postgres
#      password: postgres

logging:
  level:
    root: info
    org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer: WARN
    org.springframework.boot.web.embedded.netty.NettyWebServer: WARN
    org.springframework.boot.devtools.env.DevToolsPropertyDefaultsPostProcessor: WARN
    org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver: WARN

springdoc:
  writer-with-order-by-keys: true
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true

lergo:
  env:
    channel:
      - code: 100
        name: AAA
      - code: 200
        name: BBB