application:
    title: application.title:(@application.artifactId@)
    version: application.version:(@application.version@)
server:
    port: 8080

management:
    info:
        git:
            mode: full
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
#    webflux.base-path: /api
#    datasource:
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://localhost/postgres
#        username: postgres
#        password:

lergo:
    swagger:
        enable: false
    #        base-path: /swagger-test-api
    env:
        channel:
            - code: 100
              name: AAA
            - code: 200
              name: BBB