application:
    title: application.title:(@application.artifactId@)
    version: application.version:(@application.version@)
server:
    port: 8080

management:
    info:
        git:
            mode: full
    endpoints:
        web:
            exposure:
                include: '*'

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/postgres
        username: postgres
        password:

lergo:
    swagger:
        enable: true
    env:
        channel:
            - code: 11
              name: AAA
            - code: 22
              name: BBB