management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: 'info,health'

spring:
  application:
    name: @project.name@
    artifactId: @project.artifactId@
    version: @project.version@
    description: @project.description@

logging:
  level:
    root: info
    org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer: WARN
    org.springframework.boot.devtools.env.DevToolsPropertyDefaultsPostProcessor: WARN
    org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver: WARN
    org.springframework.boot.web.embedded.netty.NettyWebServer: WARN
    org.springframework.integration.endpoint.EventDrivenConsumer: WARN
    org.springframework.integration.channel.PublishSubscribeChannel: WARN
    org.springdoc.api.AbstractOpenApiResource: WARN

#https://springdoc.org/#properties
springdoc:
  writer-with-order-by-keys: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: true
    enabled: false
  api-docs:
    enabled: false