management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: 'info,health'

spring:
  application:
    name: @project.name@
    description: @project.description@
    artifactId: @project.artifactId@
    version: @project.version@

logging:
  level:
    root: info
    org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer: ERROR
    #org.springframework.boot.web.embedded.netty.NettyWebServer: WARN
    org.springframework.boot.devtools.env.DevToolsPropertyDefaultsPostProcessor: WARN
    org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver: WARN
    org.springdoc.api.AbstractOpenApiResource: WARN

springdoc:
  api-docs:
    enabled: false
  writer-with-order-by-keys: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: true
#  writer-with-default-pretty-printer: true
#  override-with-generic-response: true
#  api-docs:
#    resolve-schema-properties: true

lergo:
  channel:
    - code: 100
      name: AAA
    - code: 200
      name: BBB